name: 'Repository Roster'
description: 'Shout-out supporters in your GitHub README file'
author: 'varunsridharan'
branding:
  icon: 'users'
  color: 'green'

inputs:
  IMAGE_SAVE_PATH:
    description: 'Custom Location On Where To Save Images if FORK_OUTPUT_TYPE / STARS_OUTPUT_TYPE used as image'
    default: '.github/roster/'
    required: false

  FORK:
    description: 'Set True Generate latest Forked users information. or you can also provide the file location on where to save forked users info'
    required: false
    default: 'README.md'

  FORK_OUTPUT_TYPE:
    description: 'You can set the output type of forked users information. it can be either [markdown / image].'
    required: false
    default: 'table'

  FORK_COUNTS:
    description: 'No of Latest Forked Users Information To Show.'
    required: false
    default: '7'

  FORK_OUTPUT_STYLE:
    description: 'Style options for [markdown / image].'
    required: false
    default: ''

  FORK_DESCRIPTION:
    description: 'Custom Description to Show Below Forked Users Information'
    required: false
    default: ''

  STARS:
    description: 'Set True Generate Latest starred users information. or you can also provide the file location on where to save starred users info'
    required: false
    default: 'README.md'

  STARS_OUTPUT_TYPE:
    description: 'You can set the output type of starred users information. it can be either [markdown / image].'
    required: false
    default: 'table'

  STARS_COUNTS:
    description: 'No of Latest starred Users Information To Show.'
    required: false
    default: '7'

  STARS_OUTPUT_STYLE:
    description: 'Style options for [markdown / image].'
    required: false
    default: ''

  STARS_DESCRIPTION:
    description: 'Custom Description to Show Below starred Users Information'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.IMAGE_SAVE_PATH }}
    - ${{ inputs.FORK }}
    - ${{ inputs.FORK_OUTPUT_TYPE }}
    - ${{ inputs.FORK_COUNTS }}
    - ${{ inputs.FORK_DESCRIPTION }}
    - ${{ inputs.STARS }}
    - ${{ inputs.STARS_OUTPUT_TYPE }}
    - ${{ inputs.STARS_COUNTS }}
    - ${{ inputs.STARS_DESCRIPTION }}