name: "🙏 Repository Roster Examples"

on:
  workflow_dispatch:
  watch:
    types:
      - started
  fork:

jobs:
  update_examples:
    if: github.repository == 'varunsridharan/action-repository-roster'
    name: "🐔  Update Examples"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "🐔  Table Layout - default"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          STARS: 'examples/table/default.md'
          FORK: 'examples/table/default.md'
          STARS_OUTPUT_STYLE: "default"
          FORK_OUTPUT_STYLE: "default"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  Table Layout - no-image"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          STARS: 'examples/table/no-image.md'
          FORK: 'examples/table/no-image.md'
          STARS_OUTPUT_STYLE: "no-image"
          FORK_OUTPUT_STYLE: "no-image"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  Table Layout - img-small"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          STARS: 'examples/table/img-small.md'
          FORK: 'examples/table/img-small.md'
          STARS_OUTPUT_STYLE: "img-small"
          FORK_OUTPUT_STYLE: "img-small"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  Table Layout - img-large"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          STARS: 'examples/table/img-large.md'
          FORK: 'examples/table/img-large.md'
          STARS_OUTPUT_STYLE: "img-large"
          FORK_OUTPUT_STYLE: "img-large"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  Table Layout - no-name"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          STARS: 'examples/table/no-name.md'
          FORK: 'examples/table/no-name.md'
          STARS_OUTPUT_STYLE: "no-name"
          FORK_OUTPUT_STYLE: "no-name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  Table Layout - no-link"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          STARS: 'examples/table/no-link.md'
          FORK: 'examples/table/no-link.md'
          STARS_OUTPUT_STYLE: "no-link"
          FORK_OUTPUT_STYLE: "no-link"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  Table Layout - bold"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          STARS: 'examples/table/bold.md'
          FORK: 'examples/table/bold.md'
          STARS_OUTPUT_STYLE: "bold"
          FORK_OUTPUT_STYLE: "bold"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  Table Layout - italic"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          STARS: 'examples/table/italic.md'
          FORK: 'examples/table/italic.md'
          STARS_OUTPUT_STYLE: "italic"
          FORK_OUTPUT_STYLE: "italic"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  Table Layout - small"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          STARS: 'examples/table/small.md'
          FORK: 'examples/table/small.md'
          STARS_OUTPUT_STYLE: "small"
          FORK_OUTPUT_STYLE: "small"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  Table Layout - multiple-style"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          STARS: 'examples/table/multiple-style.md'
          FORK: 'examples/table/multiple-style.md'
          STARS_OUTPUT_STYLE: "bold,italic,img-small"
          FORK_OUTPUT_STYLE: "bold,italic,img-small"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  List Layout - default"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          STARS: 'examples/list/default.md'
          FORK: 'examples/list/default.md'
          STARS_OUTPUT_TYPE: "list"
          FORK_OUTPUT_TYPE: "list"
          STARS_OUTPUT_STYLE: "default"
          FORK_OUTPUT_STYLE: "default"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  List Layout - list-ordered"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          STARS: 'examples/list/list-ordered.md'
          FORK: 'examples/list/list-ordered.md'
          STARS_OUTPUT_TYPE: "list"
          FORK_OUTPUT_TYPE: "list"
          STARS_OUTPUT_STYLE: "list-ordered"
          FORK_OUTPUT_STYLE: "list-ordered"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  List Layout - no-link"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          STARS: 'examples/list/no-link.md'
          FORK: 'examples/list/no-link.md'
          STARS_OUTPUT_TYPE: "list"
          FORK_OUTPUT_TYPE: "list"
          STARS_OUTPUT_STYLE: "no-link"
          FORK_OUTPUT_STYLE: "no-link"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  List Layout - italic"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          STARS: 'examples/list/italic.md'
          FORK: 'examples/list/italic.md'
          STARS_OUTPUT_TYPE: "list"
          FORK_OUTPUT_TYPE: "list"
          STARS_OUTPUT_STYLE: "italic"
          FORK_OUTPUT_STYLE: "italic"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  List Layout - bold"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          STARS: 'examples/list/bold.md'
          FORK: 'examples/list/bold.md'
          STARS_OUTPUT_TYPE: "list"
          FORK_OUTPUT_TYPE: "list"
          STARS_OUTPUT_STYLE: "bold"
          FORK_OUTPUT_STYLE: "bold"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  List Layout - small"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          STARS: 'examples/list/small.md'
          FORK: 'examples/list/small.md'
          STARS_OUTPUT_TYPE: "list"
          FORK_OUTPUT_TYPE: "list"
          STARS_OUTPUT_STYLE: "small"
          FORK_OUTPUT_STYLE: "small"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  List Layout - multiple-style"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          STARS: 'examples/list/multiple-style.md'
          FORK: 'examples/list/multiple-style.md'
          STARS_OUTPUT_TYPE: "list"
          FORK_OUTPUT_TYPE: "list"
          STARS_OUTPUT_STYLE: "bold,italic,list-ordered"
          FORK_OUTPUT_STYLE: "bold,italic,list-ordered"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  Image Layout - default"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          IMAGE_SAVE_PATH: 'examples/roster-images/default-[type].svg'
          STARS: 'examples/image/default.md'
          FORK: 'examples/image/default.md'
          STARS_OUTPUT_TYPE: "image"
          FORK_OUTPUT_TYPE: "image"
          STARS_OUTPUT_STYLE: "default"
          FORK_OUTPUT_STYLE: "default"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  Image Layout - no-image"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          IMAGE_SAVE_PATH: 'examples/roster-images/no-image-[type].svg'
          STARS: 'examples/image/no-image.md'
          FORK: 'examples/image/no-image.md'
          STARS_OUTPUT_TYPE: "image"
          FORK_OUTPUT_TYPE: "image"
          STARS_OUTPUT_STYLE: "no-image"
          FORK_OUTPUT_STYLE: "no-image"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  Image Layout - img-smooth"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          IMAGE_SAVE_PATH: 'examples/roster-images/img-smooth-[type].svg'
          STARS: 'examples/image/img-smooth.md'
          FORK: 'examples/image/img-smooth.md'
          STARS_OUTPUT_TYPE: "image"
          FORK_OUTPUT_TYPE: "image"
          STARS_OUTPUT_STYLE: "img-smooth"
          FORK_OUTPUT_STYLE: "img-smooth"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  Image Layout - img-rounded"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          IMAGE_SAVE_PATH: 'examples/roster-images/img-rounded-[type].svg'
          STARS: 'examples/image/img-rounded.md'
          FORK: 'examples/image/img-rounded.md'
          STARS_OUTPUT_TYPE: "image"
          FORK_OUTPUT_TYPE: "image"
          STARS_OUTPUT_STYLE: "img-rounded"
          FORK_OUTPUT_STYLE: "img-rounded"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  Image Layout - img-small"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          IMAGE_SAVE_PATH: 'examples/roster-images/img-small-[type].svg'
          STARS: 'examples/image/img-small.md'
          FORK: 'examples/image/img-small.md'
          STARS_OUTPUT_TYPE: "image"
          FORK_OUTPUT_TYPE: "image"
          STARS_OUTPUT_STYLE: "img-small"
          FORK_OUTPUT_STYLE: "img-small"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  Image Layout - img-large"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          IMAGE_SAVE_PATH: 'examples/roster-images/img-large-[type].svg'
          STARS: 'examples/image/img-large.md'
          FORK: 'examples/image/img-large.md'
          STARS_OUTPUT_TYPE: "image"
          FORK_OUTPUT_TYPE: "image"
          STARS_OUTPUT_STYLE: "img-large"
          FORK_OUTPUT_STYLE: "img-large"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  Image Layout - no-name"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          IMAGE_SAVE_PATH: 'examples/roster-images/no-name-[type].svg'
          STARS: 'examples/image/no-name.md'
          FORK: 'examples/image/no-name.md'
          STARS_OUTPUT_TYPE: "image"
          FORK_OUTPUT_TYPE: "image"
          STARS_OUTPUT_STYLE: "no-name"
          FORK_OUTPUT_STYLE: "no-name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  Image Layout - bold"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          IMAGE_SAVE_PATH: 'examples/roster-images/bold-[type].svg'
          STARS: 'examples/image/bold.md'
          FORK: 'examples/image/bold.md'
          STARS_OUTPUT_TYPE: "image"
          FORK_OUTPUT_TYPE: "image"
          STARS_OUTPUT_STYLE: "bold"
          FORK_OUTPUT_STYLE: "bold"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  Image Layout - italic"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          IMAGE_SAVE_PATH: 'examples/roster-images/italic-[type].svg'
          STARS: 'examples/image/italic.md'
          FORK: 'examples/image/italic.md'
          STARS_OUTPUT_TYPE: "image"
          FORK_OUTPUT_TYPE: "image"
          STARS_OUTPUT_STYLE: "italic"
          FORK_OUTPUT_STYLE: "italic"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  Image Layout - small"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          IMAGE_SAVE_PATH: 'examples/roster-images/small-[type].svg'
          STARS: 'examples/image/small.md'
          FORK: 'examples/image/small.md'
          STARS_OUTPUT_TYPE: "image"
          FORK_OUTPUT_TYPE: "image"
          STARS_OUTPUT_STYLE: "small"
          FORK_OUTPUT_STYLE: "small"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🐔  Image Layout - multiple-style"
        uses: "varunsridharan/action-repository-roster@main"
        with:
          IMAGE_SAVE_PATH: 'examples/roster-images/multiple-style-[type].svg'
          STARS: 'examples/image/multiple-style.md'
          FORK: 'examples/image/multiple-style.md'
          STARS_OUTPUT_TYPE: "image"
          FORK_OUTPUT_TYPE: "image"
          STARS_OUTPUT_STYLE: "img-rounded,img-small,bold,italic"
          FORK_OUTPUT_STYLE: "img-rounded,img-small,bold,italic"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
