name: "🙏  Roster"

on:
  workflow_dispatch:
  watch:
    types:
      - started
  fork:

jobs:
  update_latest_roster:
    if: github.repository == 'varunsridharan/action-repository-roster'
    name: "🐔  Update Latest Roster"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "🐔  Markdown - Repository Roster"
        uses: "varunsridharan/action-repository-roster@main"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
